apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oslo-vault
  namespace: argocd
spec:
  project: default
  source:
      repoURL: https://helm.releases.hashicorp.com
      chart: vault
      version: latest
      targetRevision: 0.27.0
  destination:
    server: https://kubernetes.default.svc
    namespace: oslo-vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  helm:
    values:
      - https://raw.githubusercontent.com/Trev2689/argocd-vault-of-vaults/main/usw2/usw2-td2-eks/helm/hashicorp-vault/oslo-vault-values.yaml
