apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-of-vaults
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Trev2689/argocd-vault-of-vaults.git
    path: argocd/applications
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  dependencies:
    # Add dependency for each Vault instance application
    - source:
        path: argocd/applications/copenhagen-vault.yaml
      destination:
        namespace: copenhagen-vault
    - source:
        path: argocd/applications/oslo-vault.yaml
      destination:
        namespace: oslo-vault

